# -*- coding: utf-8 -*-
"""PRODIGY_GA_02

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11MUawk3j6tc_vBLyhR4HjVfrZy7VlEbm
"""

from diffusers import StableDiffusionPipeline
import torch
from PIL import Image
import matplotlib.pyplot as plt


device = "cuda" if torch.cuda.is_available() else "cpu"
if device == "cpu":
    print("CUDA not available. Stable Diffusion will be very slow on CPU.")

pipe = StableDiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    torch_dtype=torch.float16 if device == "cuda" else torch.float32,
).to(device)

prompt = "A cute puppy sitting in a grassy field under a blue sky"

image = pipe(prompt).images[0]


plt.imshow(image)
plt.axis("off")
plt.show()